language: node_js
node_js:
  - 0.6
  - 0.8

# We want to be notified when something happens.
notifications:
  irc:
    channels:
      - "irc.freenode.org#jsx"
    on_success: change # [always|never|change] # default: always
    on_failure: change # [always|never|change] # default: always
